"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
import re
import base64

def str_to_bool(val):
    val = str(val).strip().lower()
    return val in ('true', '1', 'yes')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DOT_ENV_PATH = BASE_DIR / ".env"

if DOT_ENV_PATH.exists():
    load_dotenv(DOT_ENV_PATH)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-xq1rhglk0+4r@x9=sqv*ah7@d#5yq_v1md!0rzsrh2^+u+xyaw')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str_to_bool(os.environ.get('DEBUG', 'False'))

# Validate SECRET_KEY in production
if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise ValueError('You must set a secure SECRET_KEY in production. Generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"')

raw_hosts = os.environ['ALLOWED_HOSTS']

if raw_hosts.strip():
    ALLOWED_HOSTS = raw_hosts.split(',') + [
        '127.0.0.1', 'localhost', '0.0.0.0', 'django', 'host.docker.internal'
    ]
else:
    ALLOWED_HOSTS = [
        '127.0.0.1', 'localhost', '0.0.0.0', 'django', 'host.docker.internal'
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    "ninja",
    'ninja_extra',

    'django_celery_beat',
    'django_celery_results',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',
    'allauth.mfa',
    'corsheaders',

    "users",
    "vault",
    "depsets",
    "functions",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'users.middleware.RegistrationControlMiddleware',
]

SITE_ID = 1

CUSTOM_DOMAIN = os.environ['CUSTOM_DOMAIN']

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Redis Configuration
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
REDIS_DB = os.environ.get('REDIS_DB', '0')
REDIS_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True

# Reduce task time limits to prevent runaway resource consumption
CELERY_TASK_TIME_LIMIT = 5 * 60  # 5 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 4 * 60  # 4 minutes soft limit

# Worker configuration to prevent resource exhaustion
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100  # Recycle workers after 100 tasks
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Fetch one task at a time (better for long-running tasks)
CELERY_TASK_ACKS_LATE = True  # Acknowledge tasks after completion (prevents lost tasks)
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Requeue tasks if worker dies
CELERY_WORKER_CONCURRENCY = 2  # Limit to 2 worker processes (adjust based on available memory)

CELERY_RESULT_BACKEND = "django-db"
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_RESULTS_EXTENDED = True

# Expire task results to prevent database bloat
CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGIN_REGEXES = [
    rf"^https://[a-z0-9-]+\.{re.escape(CUSTOM_DOMAIN)}(:[0-9]+)?$",  
    rf"^https://{re.escape(CUSTOM_DOMAIN)}(:[0-9]+)?$",              
    rf'^https://{re.escape(CUSTOM_DOMAIN)}$',
    rf"^http://[a-z0-9-]+\.{re.escape(CUSTOM_DOMAIN)}(:[0-9]+)?$",  
    rf"^http://{re.escape(CUSTOM_DOMAIN)}(:[0-9]+)?$",              
    rf'^http://{re.escape(CUSTOM_DOMAIN)}$',
]

CSRF_TRUSTED_ORIGINS = [
    f'http://{CUSTOM_DOMAIN}',
    f'https://{CUSTOM_DOMAIN}',
]

# Session Cookie Configuration for Cross-Domain Auth
SESSION_COOKIE_DOMAIN = f'.{CUSTOM_DOMAIN}' if not DEBUG else None
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG  # True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 1209600  # 2 weeks

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_LOGOUT_ON_GET = True
LOGIN_REDIRECT_URL = "/accounts/auth/gate/"
LOGIN_URL = '/accounts/login/'
ACCOUNT_SIGNUP_REDIRECT_URL = "/accounts/auth/gate/"

# OIDC/Social Account Configuration
# Configure via environment variables:
#   OIDC_PROVIDER_TYPE: keycloak, authelia, authentik, or leave empty to disable
#   OIDC_CLIENT_ID: Client ID from your OIDC provider
#   OIDC_CLIENT_SECRET: Client secret from your OIDC provider
#   OIDC_SERVER_URL: Full URL to the .well-known/openid-configuration endpoint
#
# Example for Keycloak:
#   OIDC_PROVIDER_TYPE=keycloak
#   OIDC_SERVER_URL=http://keycloak:8080/realms/master/.well-known/openid-configuration
#
# Example for Authelia:
#   OIDC_PROVIDER_TYPE=authelia
#   OIDC_SERVER_URL=https://auth.example.com/.well-known/openid-configuration
#
# Example for Authentik:
#   OIDC_PROVIDER_TYPE=authentik
#   OIDC_SERVER_URL=https://authentik.example.com/application/o/{slug}/.well-known/openid-configuration

OIDC_PROVIDER_TYPE = os.environ.get('OIDC_PROVIDER_TYPE', '').lower()
OIDC_CLIENT_ID = os.environ.get('OIDC_CLIENT_ID', '')
OIDC_CLIENT_SECRET = os.environ.get('OIDC_CLIENT_SECRET', '')
OIDC_SERVER_URL = os.environ.get('OIDC_SERVER_URL', '')

# Build OIDC app configuration if provider is enabled
OIDC_APPS = []
if OIDC_PROVIDER_TYPE and OIDC_CLIENT_ID and OIDC_CLIENT_SECRET and OIDC_SERVER_URL:
    
    provider_names = {
        'keycloak': 'Keycloak',
        'authelia': 'Authelia SSO',
        'authentik': 'Authentik SSO',
    }

    if OIDC_PROVIDER_TYPE in provider_names:
        OIDC_APPS = [
            {
                "provider_id": OIDC_PROVIDER_TYPE,
                "name": provider_names[OIDC_PROVIDER_TYPE],
                "client_id": OIDC_CLIENT_ID,
                "secret": OIDC_CLIENT_SECRET,
                "settings": {
                    "server_url": OIDC_SERVER_URL
                }
            }
        ]

SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "APPS": OIDC_APPS
    }
}

# Social Account Settings - Enable Email-Based Account Linking
SOCIALACCOUNT_ADAPTER = 'users.adapters.MySocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True  # Allow automatic signup via social login
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'  # Don't force email verification for social accounts
SOCIALACCOUNT_QUERY_EMAIL = True  # Enable querying email from social provider

# Email Configuration
# Control email sending with ENABLE_EMAIL environment variable
ENABLE_EMAIL = str_to_bool(os.environ.get('ENABLE_EMAIL', '0'))

if DEBUG or not ENABLE_EMAIL:
    # Development mode or email disabled: print to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Production mode with email enabled: use SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = str_to_bool(os.environ.get('EMAIL_USE_TLS', '1'))
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@localhost')
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Kubernetes Configuration
KUBERNETES_ENABLED = str_to_bool(os.environ.get('KUBERNETES_ENABLED', 'True'))
KUBERNETES_NAMESPACE = os.environ.get('KUBERNETES_NAMESPACE', 'fnbox-functions')

# Function Execution Backend
# Options: 'kubernetes'
FUNCTION_BACKEND = os.environ.get('FUNCTION_BACKEND', 'kubernetes')

# ================================
# HTTPS & Security Settings
# ================================
# These settings are automatically enabled in production (DEBUG=False)
# but can be overridden via environment variables if needed

if not DEBUG:
    # SSL/HTTPS Settings
    SECURE_SSL_REDIRECT = str_to_bool(os.environ.get('SECURE_SSL_REDIRECT', '1'))

    # HSTS (HTTP Strict Transport Security)
    # Tells browsers to always use HTTPS for your domain
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = str_to_bool(os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', '1'))
    SECURE_HSTS_PRELOAD = str_to_bool(os.environ.get('SECURE_HSTS_PRELOAD', '1'))

    # Secure Cookies
    SESSION_COOKIE_SECURE = str_to_bool(os.environ.get('SESSION_COOKIE_SECURE', '1'))
    CSRF_COOKIE_SECURE = str_to_bool(os.environ.get('CSRF_COOKIE_SECURE', '1'))

    # Proxy SSL Header (for reverse proxy setups like Nginx/Caddy)
    # This tells Django to trust the X-Forwarded-Proto header from your reverse proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
    SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS protection
    X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking attacks

    # Referrer Policy
    SECURE_REFERRER_POLICY = 'same-origin'
else:
    # Development settings - disable HTTPS enforcement
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False